import {defineNuxtPlugin} from '#app'

import {library} from '@fortawesome/fontawesome-svg-core'
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'

import {
  faGlobe,
  faEnvelope,
  faCalendarDays,
  faClock,
  faLocationDot,
  faCircleCheck,
  faExpand,
  faDownload,
  faXmark,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCalendarCheck,
  faClockRotateLeft,
  faArrowUpRightFromSquare,
  faCircleExclamation,
  faSpinner,
  faUsers,
  faUserTie,
  faRightFromBracket,
  faArrowLeft,
  faKey,
  faMagnifyingGlass,
  faPrint,
  faCamera,
  faImage,
  faUpload,
  faPlus,
  faTrash,
  faArrowUp,
  faArrowDown,
  faUser,
  faBagShopping,
  faTag,
  faArrowRight,
  faCircleInfo,
  faBullhorn,
} from '@fortawesome/free-solid-svg-icons'
import {faFacebook, faYoutube} from '@fortawesome/free-brands-svg-icons'

library.add(
  faGlobe,
  faEnvelope,
  faFacebook,
  faYoutube,
  faCalendarDays,
  faClock,
  faLocationDot,
  faCircleCheck,
  faExpand,
  faDownload,
  faXmark,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCalendarCheck,
  faClockRotateLeft,
  faArrowUpRightFromSquare,
  faCircleExclamation,
  faSpinner,
  faUsers,
  faUserTie,
  faRightFromBracket,
  faArrowLeft,
  faKey,
  faMagnifyingGlass,
  faPrint,
  faCamera,
  faImage,
  faUpload,
  faPlus,
  faTrash,
  faArrowUp,
  faArrowDown,
  faUser,
  faBagShopping,
  faTag,
  faArrowRight,
  faCircleInfo,
  faBullhorn,
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
})
